[package]
name = "chip-8"
version = "0.1.0"
authors = ["shorii"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
log4rs = "0.13.0"
log = "0.4.11"
console = { path = "../console" }